---
title: "Guided Exercise 3"
author: "Ted Getselman"
date: "10/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data entry and cleanup
```{r data_work}
library(tidyverse)
all_states <- map_data("state")
congress<-read_csv("womenincongress.csv")
names(congress)[2] <- "region"
stateData <- left_join(all_states,congress,by="region")
```

##Graph 1
```{r graph1}
stateData$repProp <- stateData$representatives/stateData$total
housePlot <- ggplot()+geom_polygon(data=stateData,aes(x=long, y=lat, group = group, fill=repProp),color="grey50")+coord_map()+labs(x="",y="",title="Women in the House")+theme_classic()+ theme(axis.ticks.y = element_blank(),axis.text.y = element_blank(), axis.ticks.x = element_blank(),axis.text.x = element_blank()) + scale_fill_gradient(name="Female Representatives",low="whitesmoke",high="darkred")
housePlot
```

##Graph 2
```{r graph2} 
electionData <- read_csv("2012.csv")
names(electionData)[1] <- "region"
electionData$ObamaPerc <- electionData$ObamaVotes/(electionData$ObamaVotes+electionData$RomneyVotes+electionData$JohnsonVotes+electionData$SteinVotes)
electionData <- merge(all_states,electionData,by="region")
south <- filter(electionData, region %in% c("texas", "oklahoma", "arkansas", "louisiana", "alabama", "mississippi", "tennessee", "georgia", "florida", "south carolina", "north carolina", "virginia", "west virginia", "kentucky", "maryland", "delaware", "district of columbia"))
SouthPlot <- ggplot()+geom_polygon(data=south,aes(x=long, y=lat, group = group, fill=ObamaPerc),color="grey50")+coord_map()+labs(x="",y="",title="2012 Election Results")+theme_classic()+ theme(axis.ticks.y = element_blank(),axis.text.y = element_blank(), axis.ticks.x = element_blank(),axis.text.x = element_blank()) + scale_fill_gradient2(name="Obama's Percenatage",low="red",mid="white",high="blue",midpoint=.5)
SouthPlot
```